### ISSUE TITLE
Error: Can't extend QueryBuilder with existing method ('cache').

### ISSUE THREAD

**Issue by BoryaMogila** [cvburgess/SQLDataSource#32]
reproduce when you have two extended classes

**Comment by cvburgess** [comment]
Can you please provide a usage example?

I can imagine how this could happen but seeing the usage will help

**Comment by rafagsiqueira** [comment]
I had the same problem here. In my case it happened because I was returning an object instead of a String for one of the fields.

**Comment by johnayoung** [comment]
Same issue here. Maybe I can provider a clearer example of what i'm trying to do:

```
  async getUsers(args) {
    const q = await this.db
      .select()
      .from(users)
      .modify(queryBuilder => {
        if (args) {
          queryBuilder.where(args);
        }
      });
    // .cache(MINUTE);

    return Array.isArray(q) ? q.map(user => this.userReducer(user)) : [];
  }

  async getUser(args) {
    const query = await this.db
      .select('*')
      .from(users)
      .modify(queryBuilder => {
        if (args) {
          queryBuilder.where(args);
        }
      });
    // .cache(MINUTE);

    // return this.getBatchedAndCached(query, MINUTE);
    return !Array.isArray(query) || !query.length
      ? null
      : this.userReducer(query[0]);
  }

  async userReducer(user) {
    return {
      ...user,
    };
  }
```

The error message returned from Apollo is:

```
{
  "error": {
    "errors": [
      {
        "message": "Can't extend QueryBuilder with existing method ('cache').",
        "extensions": {
          "code": "INTERNAL_SERVER_ERROR",
          "exception": {
            "stacktrace": [
              "Error: Can't extend QueryBuilder with existing method ('cache').",
              "    at Function.Builder.extend (C:\\Users\\JYoun\\Code\\projects\\cryptosheets\\node_modules\\knex\\lib\\query\\builder.js:1276:11)",
              "    at Object.extend (C:\\Users\\JYoun\\Code\\projects\\cryptosheets\\node_modules\\knex\\lib\\knex.js:63:18)",
              "    at new SQLDataSource (C:\\Users\\JYoun\\Code\\projects\\cryptosheets\\node_modules\\datasource-sql\\index.js:20:23)",
              "    at new ParadigmDB (C:\\Users\\JYoun\\Code\\projects\\cryptosheets\\packages\\cs-graphql\\datasources\\paradigmdb.js:16:1)",
              "    at Object.dataSources (C:\\Users\\JYoun\\Code\\projects\\cryptosheets\\packages\\cs-graphql\\index.js:49:17)",
              "    at initializeDataSources (C:\\Users\\JYoun\\Code\\projects\\cryptosheets\\node_modules\\apollo-server-core\\dist\\requestPipeline.js:313:44)",
              "    at Object.<anonymous> (C:\\Users\\JYoun\\Code\\projects\\cryptosheets\\node_modules\\apollo-server-core\\dist\\requestPipeline.js:46:9)",
              "    at Generator.next (<anonymous>)",
              "    at C:\\Users\\JYoun\\Code\\projects\\cryptosheets\\node_modules\\apollo-server-core\\dist\\requestPipeline.js:8:71",
              "    at new Promise (<anonymous>)",
              "    at __awaiter (C:\\Users\\JYoun\\Code\\projects\\cryptosheets\\node_modules\\apollo-server-core\\dist\\requestPipeline.js:4:12)",
              "    at Object.processGraphQLRequest (C:\\Users\\JYoun\\Code\\projects\\cryptosheets\\node_modules\\apollo-server-core\\dist\\requestPipeline.js:41:12)",
              "    at C:\\Users\\JYoun\\Code\\projects\\cryptosheets\\node_modules\\apollo-server-core\\dist\\runHttpQuery.js:162:62",
              "    at Generator.next (<anonymous>)",
              "    at C:\\Users\\JYoun\\Code\\projects\\cryptosheets\\node_modules\\apollo-server-core\\dist\\runHttpQuery.js:8:71",
              "    at new Promise (<anonymous>)",
              "    at __awaiter (C:\\Users\\JYoun\\Code\\projects\\cryptosheets\\node_modules\\apollo-server-core\\dist\\runHttpQuery.js:4:12)",
              "    at processHTTPRequest (C:\\Users\\JYoun\\Code\\projects\\cryptosheets\\node_modules\\apollo-server-core\\dist\\runHttpQuery.js:98:12)",
              "    at Object.<anonymous> (C:\\Users\\JYoun\\Code\\projects\\cryptosheets\\node_modules\\apollo-server-core\\dist\\runHttpQuery.js:93:16)",
              "    at Generator.next (<anonymous>)",
              "    at fulfilled (C:\\Users\\JYoun\\Code\\projects\\cryptosheets\\node_modules\\apollo-server-core\\dist\\runHttpQuery.js:5:58)",
              "    at process._tickCallback (internal/process/next_tick.js:68:7)"
            ]
          }
        }
      }
    ]
  }
}
```

**Comment by cvburgess** [comment]
Awesome - ty. I think i have a fix for this by extending the method outside of the class.

**Comment by johnayoung** [comment]
> Awesome - ty. I think i have a fix for this by extending the method outside of the class.

Nice! Also, thanks for building this. Really is helping us out.

**Comment by mateuszgachowski** [comment]
Hi guys, any info about this one? Having the same issue sadly :(

**Comment by BoryaMogila** [comment]
I make [pull request](url) to fix it.

**Comment by cvburgess** [comment]
I'm still struggling to reproduce?

@BoryaMogila your PR covers a _lot of things_ not just this, so I'm not comfortable merging that yet. If you'd like to open a smaller PR for just this scenario, I would greatly appreciate it.

**Comment by BoryaMogila** [comment]
ok

**Comment by BoryaMogila** [comment]
make pull request

**Comment by cvburgess** [comment]
This was fixed in v1.0.2, sorry for the delay - reproducing was difficult.

If you use this module as recommended ( not calling `new` in the Apollo context creation ) this issue would not appear.

The update supports calling `new` anywhere you would like, but be warned, Knex pooling occurs when you call `new` so IMO it may be best to do that once per app, not on every request. ( I may be wrong )

**Comment by rjbobeles** [comment]
This might still an issue with the current version of SQLDataSource. Instantiating 2 SQLDataSource classes using the same Knex instance will give this error:

`Error: Can't extend QueryBuilder with existing method ('cache').`

sqlContext
```
import Knex from 'Knex'

const sqlContext = Knex({
  client: 'sqlite',
  connection: {
    filename: './gql.sqlite',
  },
  migrations: {
    tableName: 'migrations',
  },
  useNullAsDefault: true,
})
```

(Called before context creation)
```
const peopleDataSources = new PeopleDataSource(sqlContext)
const petsDataSources = new PetsDataSource(sqlContext)
```

As of now, the only solution I found is to instantiate Knex from the class itself
```
const peopleDataSources = new PeopleDataSource({
  client: 'sqlite',
  connection: {
    filename: './gql.sqlite',
  },
  migrations: {
    tableName: 'migrations',
  },
  useNullAsDefault: true,
})
```

**Comment by rjbobeles** [comment]
This appears to still be an issue with the current version of SQLDataSource. Instantiating 2 SQLDataSource classes using the same Knex instance will give this error:

`Error: Can't extend QueryBuilder with existing method ('cache').`

sqlContext
```
import Knex from 'Knex'

const sqlContext = Knex({
  client: 'sqlite',
  connection: {
    filename: './gql.sqlite',
  },
  migrations: {
    tableName: 'migrations',
  },
  useNullAsDefault: true,
})
```

(Called before context creation)
```
const peopleDataSources = new PeopleDataSource(sqlContext)
const petsDataSources = new PetsDataSource(sqlContext)
```

As of now, the only solution I found is to instantiate Knex from the class itself
```
const peopleDataSources = new PeopleDataSource({
  client: 'sqlite',
  connection: {
    filename: './gql.sqlite',
  },
  migrations: {
    tableName: 'migrations',
  },
  useNullAsDefault: true,
})
```

**Comment by cvburgess** [comment]
Youre welcome to open a PR for this!
Im a little short on time but happy to review and merge.

**Comment by abv** [comment]
My ~~solution~~ hack is to create a single monkeypatched instance of knex w/ the `cache` method extended, and pass that monkeypatched instance to each class that extends SQLDataSource. If you pass the knex config to each class, you lose out on connection pooling.

```const sqlContext = Knex({...})

const dataSource = new SQLDataSource(knex);
dataSource.db.cache = true;

const peopleDataSources = new PeopleDataSource(dataSource.knex)
const petsDataSources = new PetsDataSource(dataSource.knex)
```

I _think_ the bug is that when cache is extended here https://github.com/cvburgess/SQLDataSource/blob/dd6a87bdace4d3e5a0649ea28d3485f037e3c656/index.js#L27-L31 there is no logic that sets `this.db.cache` to true. @cvburgess If the proper fix is to just add a `this.db.cache = true` after line 27, happy to make a PR to do so.

**Comment by AD-Vincent** [comment]
Hello, I still have the error `Cannot set properties of undefined (setting 'cache')` when I try to instantiate 2 SQLDataSource.

My process create a unique knex connection (when the application starts) , then I pass in my classes extending SQLDataSource this unique knex connection.

The first instance of SQLDataSource is correct, but the second raise the error.

```typescript
// unique SqlClient created in the application with the knex connection
export class SqlClient {
  private readonly config: any;
  public connection: Knex<any, unknown[]>; // this connection should be injected in every SQLDataSources implementation

  constructor(myConfiguration) {
    this.config = myConfiguration
  }

  connect() {
    this.connection = knex(this.config);
  }
}
```

```typescript
// create my own model extending SQLDataSource
export class MySQLDataSource extends SQLDataSource {

  constructor(client: SqlClient) {
    super(client.connection);
  }
}
```

```typescript
// create unique knex connection and inject in SQLDataSources implementations
const sqlClient = new SqlClient(myConfiguration);
sqlClient.connect(); //OK

const foo = new MySQLDataSource(sqlClient.connection); //OK
const bar = new MySQLDataSource(sqlClient.connection); //raise error
```

Am I missing something ?

**Comment by cvburgess** [comment]
@AD-Vincent v1.0.2 should have resolved this.

If you are still getting the issue with the latest version we may need to re-evaluate the check logic.

If you can reproduce, feel free to open a PR with the necessary changes.

I have not used this project in several years so I don't have a great setup to test against.

**Comment by mindaugasnakrosis** [comment]
I am still facing the same error with the latest version.

**Comment by Gwiad** [comment]
this did the trick for me => https://github.com/cvburgess/SQLDataSource/issues/81#issuecomment-1157999710
